### ISSUE TITLE
Issue with qualityMetrics on InterOp NextSeq500 data

### ISSUE THREAD

**Issue by rlanos** [bcalder/savR#4]
Hi, 

I have upgraded savR from 0.99 to 1.7.5 in order to get NextSeq500 support but I've got this issue:

> library(ggplot2)
> library(savR)
> project <- savR("my_run_folder")
> project
> savProject instance with 4 lanes, 160 total cycles, and 3 sequence reads ( 2 sequencing and  1 indexed reads ).
>  Indicated tile naming convention: FiveDigit.
>  With InterOp data for:  savCorrectedIntensityFormat (correctedIntensities)
>   savQualityFormatV5 (qualityMetrics)
>   savTileFormat (tileMetrics)
>   savExtractionFormat (extractionMetrics)
> 
> quality = qualityMetrics(project)
> Error in qualityMetrics(project) : 
>   trying to get slot "data" from an object of a basic class ("NULL") with no slots
> quality
> Error: object 'quality' not found

**Comment by ploverso-pgdx** [comment]
I'm not sure if the maintainer of this repository is still working on this project, but I have a fork I'm currently working on that fixes this bug, as well as adding support for sequencers running RTA v.2.7.1 or newer and (soon) also outputting index metrics.

https://github.com/ploverso-pgdx/savR

**Comment by bcalder** [comment]
I recently moved positions and need to update contact info.  If you can send a pull request for your bug fix, I can merge it.

thanks,

brent

**Comment by ploverso-pgdx** [comment]
For some reason, my repo isn't showing up under the forks on your pull request page. ~~Until I work that out, here's the patch file for the bugfix:
https://github.com/ploverso-pgdx/savR/commit/a4509573f8a8c0acf789b1316820ec82742f74ee.patch~~

Remade the repo by forking you, pull request submitted

**Comment by rlanos** [comment]
The fix is working right. I downloaded the zip of your bugfix branch and then type, in R, the command install("/path/to/unziped/bugfix/branch") from devtools package.

**Comment by ploverso-pgdx** [comment]
Pull request has been submitted

**Comment by ploverso-pgdx** [comment]
Just a note, if you don't have devtools installed, you can install from source with:
install.packages(path_to_folder_or_zip, repos = NULL, type="source")
